# Generated by Django 4.2.7 on 2023-11-22 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='temporaryattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
