# Generated by Django 4.2.7 on 2023-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_archiveattendance_date_temporaryattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryattendance',
            name='timeout_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
