# Generated by Django 4.2.7 on 2023-12-28 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_temporaryattendance_timeout_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveAttendance',
        ),
        migrations.AddField(
            model_name='temporaryattendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
