# Generated by Django 4.2.7 on 2023-12-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_archiveattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryattendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
