# Generated by Django 4.2.7 on 2023-12-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_temporaryattendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='student',
        ),
    ]
