# Generated by Django 4.2.7 on 2023-12-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_temporaryattendance_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='student_code',
        ),
    ]
