# Generated by Django 4.2.7 on 2023-12-06 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_temporaryattendance_student_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('BranchCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('BranchName', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=150)),
                ('NumEmps', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Firstname', models.CharField(max_length=20)),
                ('Middlename', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('DateofBirth', models.DateField()),
                ('BloodType', models.CharField(max_length=3)),
                ('Gender', models.CharField(max_length=8)),
                ('CivilStatus', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=20)),
                ('EmployementDate', models.DateField()),
                ('EmploymentStatus', models.CharField(max_length=15)),
                ('BranchCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HasLocator', models.BooleanField()),
                ('OnLeave', models.BooleanField()),
                ('HasTripTicket', models.BooleanField()),
                ('StatusDate', models.DateField(default=datetime.date.today)),
                ('Remarks', models.CharField(max_length=100)),
                ('EmpCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timein', models.CharField(blank=True, max_length=8, null=True)),
                ('timeout', models.CharField(blank=True, max_length=8, null=True)),
                ('breakout', models.CharField(blank=True, max_length=8, null=True)),
                ('breakin', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeout_updated', models.DateTimeField(blank=True, null=True)),
                ('EmpCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCount',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Vacation', models.IntegerField(max_length=3)),
                ('Sick', models.IntegerField(max_length=3)),
                ('GracePeriod', models.IntegerField(max_length=3)),
                ('EmpCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
