# Generated by Django 4.2.7 on 2023-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_branches_employee_employeestatus_dailyrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='abbr',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancecount',
            name='GracePeriod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancecount',
            name='Sick',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancecount',
            name='Vacation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branches',
            name='Location',
            field=models.CharField(max_length=50),
        ),
    ]
