# Generated by Django 4.2.7 on 2023-12-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_branches_abbr_alter_attendancecount_graceperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('FormID', models.AutoField(primary_key=True, serialize=False)),
                ('SelectRequest', models.CharField(max_length=30)),
                ('BeginTimeOff', models.DateField()),
                ('ConcludeTimeOff', models.DateField()),
                ('isApproved', models.BooleanField(default=False)),
                ('Remarks', models.CharField(max_length=100)),
                ('EmpCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
