# Generated by Django 4.2.7 on 2023-12-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_requestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
