# Generated by Django 4.2.7 on 2023-12-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Position',
            field=models.CharField(max_length=50),
        ),
    ]
