# Generated by Django 4.2.7 on 2023-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_employee_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TemporaryAttendance',
        ),
        migrations.AlterField(
            model_name='requestform',
            name='BeginTimeOff',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='ConcludeTimeOff',
            field=models.DateTimeField(),
        ),
    ]
