# Generated by Django 4.2.7 on 2023-12-19 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_student_delete_temporaryattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
