# Generated by Django 4.2.7 on 2023-12-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_attendancecount_sick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='Range',
            field=models.CharField(default='AM', max_length=10),
        ),
    ]
