# Generated by Django 4.2.7 on 2023-12-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_requestform_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='Range',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
