# Generated by Django 4.2.7 on 2023-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_requestform_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='totallateness',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
