# Generated by Django 4.2.7 on 2023-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dailyrecord_totallateness'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='totalundertime',
            field=models.CharField(default='00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='totallateness',
            field=models.CharField(default='00:00', max_length=8),
        ),
    ]
