# Generated by Django 4.2.7 on 2023-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_dailyrecord_totalundertime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='breakin',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='breakout',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='timein',
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
