# Generated by Django 4.2.7 on 2023-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_dailyrecord_breakin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='breakin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='breakout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
