# Generated by Django 4.2.7 on 2023-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_dailyrecord_breakin_dailyrecord_breakout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='totalovertime',
            field=models.CharField(default='00:00', max_length=8),
        ),
    ]
