# Generated by Django 4.2.7 on 2023-12-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_dailyrecord_totalovertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approveOT',
            field=models.BooleanField(default=False),
        ),
    ]
