# Generated by Django 4.2.7 on 2023-12-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_dailyrecord_breakin_alter_dailyrecord_breakout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='breakin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='breakout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
