# Generated by Django 4.2.7 on 2023-12-21 01:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_dailyrecord_breakin_alter_dailyrecord_breakout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timein_names', models.CharField(blank=True, max_length=100, null=True)),
                ('timeout_names', models.CharField(blank=True, max_length=100, null=True)),
                ('breakout_names', models.CharField(blank=True, max_length=100, null=True)),
                ('breakin_names', models.CharField(blank=True, max_length=100, null=True)),
                ('timein_timestamps', models.DateTimeField(blank=True, null=True)),
                ('breakout_timestamps', models.DateTimeField(blank=True, null=True)),
                ('breakin_timestamps', models.DateTimeField(blank=True, null=True)),
                ('timeout_timestamps', models.DateTimeField(blank=True, null=True)),
                ('afternoonBreakout_timestamps', models.DateTimeField(blank=True, null=True)),
                ('afternoonTimeout_timestramps', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archive',
            },
        ),
        migrations.CreateModel(
            name='TemporaryAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timein', models.CharField(blank=True, max_length=8, null=True)),
                ('timeout', models.CharField(blank=True, max_length=8, null=True)),
                ('breakout', models.CharField(blank=True, max_length=8, null=True)),
                ('breakin', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'temporary',
            },
        ),
    ]
