# Generated by Django 4.2.7 on 2023-12-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_archive_temporaryattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='name',
            new_name='employee_number',
        ),
        migrations.RenameField(
            model_name='temporaryattendance',
            old_name='name',
            new_name='employee_number',
        ),
    ]
