# Generated by Django 4.2.7 on 2023-12-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_name_archive_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryattendance',
            name='breakin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryattendance',
            name='breakout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryattendance',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryattendance',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
