# Generated by Django 4.2.7 on 2023-12-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_temporaryattendance_breakin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='temporray',
        ),
        migrations.DeleteModel(
            name='TemporaryAttendance',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='timeout_updated',
        ),
        migrations.AlterModelTable(
            name='temporray',
            table='temporay',
        ),
    ]
