# Generated by Django 4.2.7 on 2023-12-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_archive_temporray_delete_temporaryattendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='approveOT',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='approveOT',
            field=models.BooleanField(default=False),
        ),
    ]
