# Generated by Django 4.2.7 on 2023-12-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_employee_approveot_dailyrecord_approveot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='approveOT',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
