# Generated by Django 4.2.7 on 2023-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_dailyrecord_approveot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecount',
            name='GracePeriod',
            field=models.IntegerField(default=15),
        ),
    ]
