# Generated by Django 4.2.7 on 2023-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_attendancecount_graceperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecount',
            name='last_reset_month',
            field=models.IntegerField(default=0),
        ),
    ]
