# Generated by Django 4.2.7 on 2023-12-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_branches_branchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpImage',
            field=models.ImageField(blank=True, null=True, upload_to='emp_image/'),
        ),
    ]
