# Generated by Django 4.2.7 on 2024-01-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_branches_abbr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='BranchName',
            new_name='Company',
        ),
    ]
