# Generated by Django 4.2.7 on 2024-01-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_branchname_branches_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='NumEmps',
            new_name='Employees',
        ),
    ]
