# Generated by Django 4.2.7 on 2024-01-02 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rename_numemps_branches_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Address',
            field=models.CharField(default='N/D', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='BloodType',
            field=models.CharField(default='N/D', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DateofBirth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployementDate',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
