# Generated by Django 4.2.7 on 2024-01-03 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_employee_address_alter_employee_bloodtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecount',
            name='last_grace_period_month',
            field=models.DateTimeField(default=datetime.date(2024, 1, 1)),
        ),
    ]
