# Generated by Django 4.2.7 on 2024-01-03 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_attendancecount_last_grace_period_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecount',
            name='last_leaves_year',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
