# Generated by Django 4.2.7 on 2024-01-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_attendancecount_last_leaves_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='totallateness',
            field=models.CharField(default='00:00', max_length=50),
        ),
    ]
