# Generated by Django 4.2.7 on 2024-01-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_employeestatus_haslocator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestatus',
            name='EmpCode',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='LateCount',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='UndertimeCount',
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='DailyRecord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dailyrecord'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='RequestForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.requestform'),
        ),
    ]
