# Generated by Django 4.2.7 on 2024-01-05 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_employeestatus_empcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='RequestDate',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
