# Generated by Django 4.2.7 on 2024-01-07 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_employeestatus_requestdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
