# Generated by Django 4.2.7 on 2024-01-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_requestform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='latecount',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
