# Generated by Django 4.2.7 on 2024-01-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_dailyrecord_latecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestatus',
            name='DailyRecord',
        ),
    ]
