# Generated by Django 4.2.7 on 2024-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_employeestatus_dailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecount',
            name='Sick',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancecount',
            name='Vacation',
            field=models.FloatField(default=0),
        ),
    ]
