# Generated by Django 4.2.7 on 2024-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_attendancecount_sick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='Empname',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='temporray',
            name='Empname',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
