# Generated by Django 4.2.7 on 2024-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_dailyrecord_empname_temporray_empname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='Empname',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='temporray',
            name='Empname',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
