# Generated by Django 4.2.7 on 2024-01-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_alter_dailyrecord_empname_alter_temporray_empname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporray',
            old_name='afternoonBreakout_timestamps',
            new_name='afternoonBreakin_timestamps',
        ),
    ]
