# Generated by Django 4.2.7 on 2024-01-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_rename_afternoonbreakout_timestamps_temporray_afternoonbreakin_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='discrepancy',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
