# Generated by Django 4.2.7 on 2024-01-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_dailyrecord_discrepancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='discrepancy',
            new_name='absent',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='late',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
