# Generated by Django 4.2.7 on 2024-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_rename_discrepancy_dailyrecord_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='totalabsent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totallateness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totalovertime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totalundertime',
            field=models.FloatField(default=0),
        ),
    ]
