# Generated by Django 4.2.7 on 2024-01-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_employeestatus_totalabsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='DailyRecord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dailyrecord'),
        ),
    ]
