# Generated by Django 4.2.7 on 2024-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_remove_employeestatus_dailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='totalovertime',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
