# Generated by Django 4.2.7 on 2024-01-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_alter_dailyrecord_totalovertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='remarks',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
