# Generated by Django 4.2.7 on 2024-02-07 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_dailyrecord_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='requestform',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 7)),
        ),
    ]
