# Generated by Django 4.2.7 on 2024-02-27 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_dailyrecord_grace_alter_requestform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='grace',
        ),
        migrations.AlterField(
            model_name='requestform',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
    ]
