# Generated by Django 4.2.7 on 2024-02-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_remove_dailyrecord_grace_alter_requestform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='BranchCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.branches'),
        ),
    ]
