# Generated by Django 4.2.7 on 2024-02-15 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_alter_employee_branchcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='memo',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 15)),
        ),
    ]
