# Generated by Django 4.2.7 on 2024-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_dailyrecord_memo_alter_requestform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='memo',
        ),
        migrations.AddField(
            model_name='attendancecount',
            name='memo',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
