# Generated by Django 4.2.7 on 2024-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_alter_dailyrecord_remarks_alter_requestform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='remarks',
            field=models.CharField(default='None', max_length=400),
        ),
    ]
